-- CreateEnum
CREATE TYPE "ReportReason" AS ENUM ('INAPPROPRIATE_CONTENT', 'MISLEADING_OR_FALSE_INFO', 'SPAM_OR_DUPLICATE', 'PRIVACY_VIOLATION', 'HARASSMENT_OR_HATE_SPEECH', 'OTHER');

-- AlterTable
ALTER TABLE "Interaction" ADD COLUMN     "reportReason" "ReportReason",
ADD COLUMN     "text" TEXT;
